# Generated by Django 4.2.14 on 2024-08-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo/', verbose_name='Лого')),
                ('name', models.CharField(max_length=1024, verbose_name='Имя')),
                ('description', models.TextField(max_length=102400, verbose_name='Описание')),
            ],
        ),
    ]
